export enum ErrorCode {
    // Authentication Errors
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID",

    // Unique Constraint Errors
    UNIQUE = "UNIQUE",

    // User Errors
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
    USERNAME_EXISTS = "USERNAME_EXISTS",
    USERNAME_SAME_FORBIDDEN = "USERNAME_SAME_FORBIDDEN",
    EMAIL_EXISTS = "EMAIL_EXISTS",

    // Email Verification Errors
    EMAIL_VERIFICATION_INVALID = "EMAIL_VERIFICATION_INVALID",
    EMAIL_VERIFICATION_USED = "EMAIL_VERIFICATION_USED",

    // Password Errors
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT",
    PASSWORD_RESET_INVALID = "PASSWORD_RESET_INVALID",
    PASSWORD_RESET_USED = "PASSWORD_RESET_USED",

    // Account Recovery Errors
    ACCOUNT_RECOVERY_INVALID = "ACCOUNT_RECOVERY_INVALID",

    // OTP Errors
    OTP_INVALID_OR_EXPIRED = "OTP_INVALID_OR_EXPIRED",

    // Account Management Errors
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",

    // Trade Errors
    TRADE_NOT_FOUND = "TRADE_NOT_FOUND",
    TRADES_NOT_FOUND = "TRADES_NOT_FOUND",

    // Playbook Errors
    PLAYBOOK_NOT_FOUND = "PLAYBOOK_NOT_FOUND",

    // Rate Limiting Errors
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

    // Server Errors
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}